
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Turma01
 */
public class Calc extends javax.swing.JFrame {
     private double vtmp;

    public double getVtmp() {
        return vtmp;
    }

    public void setVtmp(double vtmp) {
        this.vtmp = vtmp;
    }
     private boolean st; // status dos botoes  operacoes
     private String op;

    public String getOp() {
        return op;
    }

    public void setOp(String op) {
        this.op = op;
    }

    
    private boolean btigual;
    
     
    private double SB;
    private double RS;
    private double SM;

    
    
    public boolean isBtigual() {
        return btigual;
    }

    public void setBtigual(boolean btigual) {
        this.btigual = btigual;
    }
    
    

    public boolean isSt() {
        return st;
    }

    public void setSt(boolean st) {
        this.st = st;
    }

    public double getValor() {
        return vtmp;
    }

    public void setValor(double valor) {
        this.vtmp = vtmp;
//        this.btigual= btigual;
    }
    
    
    private void Calcula(String op){
       
        double result =0;
        double display = Double.parseDouble(textResult.getText());
        
        switch(op){
            case "+" :
                result = vtmp + display;
                break;
            case "-":
                result = vtmp - display;
                break;
            case "*":
//                JOptionPane.showMessageDialog(null,evt.getActionCommand() );
                result = vtmp * display;
                break;
            case "/":
                result = vtmp / display;
                break;    
            
            default:
        }
        Mostrar(result);
        setSt(true);
        setBtigual(true);
    }
    
    private void Mostrar(double vl){
        DecimalFormat  format = new DecimalFormat("0.########");
       textResult.setText(String.valueOf(format.format(vl)));
        
    }
    
     private void Iniciar() {
        this.vtmp=0;
        this.st = true;
        this.btigual= false;
        
//        textResult.setText("0");
//        textResult.requestFocusInWindow();

    }

    public Calc() {
        initComponents();
        Iniciar();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textResult = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        bnt2 = new javax.swing.JButton();
        bnt3 = new javax.swing.JButton();
        bntPonto = new javax.swing.JButton();
        bntSub = new javax.swing.JButton();
        bntAdc = new javax.swing.JButton();
        bntMult = new javax.swing.JButton();
        bntDiv = new javax.swing.JButton();
        bntVoltar = new javax.swing.JButton();
        bnt7 = new javax.swing.JButton();
        bnt4 = new javax.swing.JButton();
        bnt6 = new javax.swing.JButton();
        bnt8 = new javax.swing.JButton();
        bnt9 = new javax.swing.JButton();
        bnt5 = new javax.swing.JButton();
        bnt1 = new javax.swing.JButton();
        bntC = new javax.swing.JButton();
        bntigual = new javax.swing.JButton();
        bnt0 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        textResult.setBackground(new java.awt.Color(153, 153, 153));
        textResult.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textResult, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textResult, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        bnt2.setBackground(new java.awt.Color(153, 153, 153));
        bnt2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bnt2.setText("2");
        bnt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt0ActionPerformed(evt);
            }
        });

        bnt3.setBackground(new java.awt.Color(153, 153, 153));
        bnt3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bnt3.setText("3");
        bnt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt0ActionPerformed(evt);
            }
        });

        bntPonto.setBackground(new java.awt.Color(153, 153, 153));
        bntPonto.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bntPonto.setText(".");
        bntPonto.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                bntPontoComponentHidden(evt);
            }
        });
        bntPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPontoActionPerformed(evt);
            }
        });

        bntSub.setBackground(new java.awt.Color(255, 51, 51));
        bntSub.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bntSub.setText("-");
        bntSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Operadores(evt);
            }
        });

        bntAdc.setBackground(new java.awt.Color(255, 51, 51));
        bntAdc.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bntAdc.setText("+");
        bntAdc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Operadores(evt);
            }
        });

        bntMult.setBackground(new java.awt.Color(255, 51, 51));
        bntMult.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bntMult.setText("*");
        bntMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Operadores(evt);
            }
        });

        bntDiv.setBackground(new java.awt.Color(255, 51, 51));
        bntDiv.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bntDiv.setText("/");
        bntDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Operadores(evt);
            }
        });

        bntVoltar.setBackground(new java.awt.Color(153, 153, 153));
        bntVoltar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bntVoltar.setText("Back");
        bntVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVoltarActionPerformed(evt);
            }
        });

        bnt7.setBackground(new java.awt.Color(153, 153, 153));
        bnt7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bnt7.setText("7");
        bnt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt0ActionPerformed(evt);
            }
        });

        bnt4.setBackground(new java.awt.Color(153, 153, 153));
        bnt4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bnt4.setText("4");
        bnt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt0ActionPerformed(evt);
            }
        });

        bnt6.setBackground(new java.awt.Color(153, 153, 153));
        bnt6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bnt6.setText("6");
        bnt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt0ActionPerformed(evt);
            }
        });

        bnt8.setBackground(new java.awt.Color(153, 153, 153));
        bnt8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bnt8.setText("8");
        bnt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt0ActionPerformed(evt);
            }
        });

        bnt9.setBackground(new java.awt.Color(153, 153, 153));
        bnt9.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bnt9.setText("9");
        bnt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt0ActionPerformed(evt);
            }
        });

        bnt5.setBackground(new java.awt.Color(153, 153, 153));
        bnt5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bnt5.setText("5");
        bnt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt0ActionPerformed(evt);
            }
        });

        bnt1.setBackground(new java.awt.Color(153, 153, 153));
        bnt1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bnt1.setText("1");
        bnt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt0ActionPerformed(evt);
            }
        });

        bntC.setBackground(new java.awt.Color(153, 153, 153));
        bntC.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bntC.setText("C");
        bntC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCbnt0ActionPerformed(evt);
            }
        });

        bntigual.setBackground(new java.awt.Color(0, 0, 255));
        bntigual.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bntigual.setText("=");
        bntigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntigualActionPerformed(evt);
            }
        });

        bnt0.setBackground(new java.awt.Color(153, 153, 153));
        bnt0.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bnt0.setText("0");
        bnt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt0ActionPerformed(evt);
            }
        });
        bnt0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bnt0KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bntVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntC, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bnt4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bnt7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bnt1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bnt5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bnt8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bnt2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(bnt0, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bnt6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bnt9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bnt3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntMult, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntSub, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntAdc, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntigual, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntC, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnt7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnt8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnt9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntMult, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnt4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnt5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnt6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntSub, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnt1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnt2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnt3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntAdc, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntigual, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnt0, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bnt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt0ActionPerformed
        // TODO add your handling code here:
//        JOptionPane.showMessageDialog(null,evt.paramString());
        if (isBtigual() ){
            setBtigual(false);
            textResult.setText("");
            this.vtmp=0;
            textResult.setText(textResult.getText() + evt.getActionCommand());
            textResult.requestFocusInWindow(); //posicionar cursor
            
        }else{
            textResult.setText(textResult.getText() + evt.getActionCommand());
            textResult.requestFocusInWindow(); //posicionar cursor
           
        }
        

    }//GEN-LAST:event_bnt0ActionPerformed

    private void bntVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVoltarActionPerformed
        // TODO add your handling code here:
        textResult.setText(textResult.getText().substring(0, textResult.getText().length() - 1));

    }//GEN-LAST:event_bntVoltarActionPerformed

    private void bnt0KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bnt0KeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_bnt0KeyTyped

    private void bntCbnt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCbnt0ActionPerformed
        // TODO add your handling code here:
        textResult.setText("");
        setSt(true);
        this.vtmp =0;
        
    }//GEN-LAST:event_bntCbnt0ActionPerformed

    private void bntPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPontoActionPerformed
        // TODO add your handling code here:
        if (textResult.getText().indexOf(".") <= 0) {
            textResult.setText(textResult.getText() + evt.getActionCommand());
        }

    }//GEN-LAST:event_bntPontoActionPerformed

    private void Operadores(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Operadores
//       JOptionPane.showMessageDialog(null,evt.paramString());
       if (isSt()){
           setVtmp(Double.parseDouble((textResult.getText())));
           setOp(evt.getActionCommand());
           setSt(false);
           textResult.setText("");


//           setSt(false);
//           JOptionPane.showMessageDialog(null,String.valueOf(vtmp));
//           JOptionPane.showMessageDialog(null,evt.getActionCommand() );
       }
    }//GEN-LAST:event_Operadores

    private void bntPontoComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_bntPontoComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_bntPontoComponentHidden

    private void textResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textResultActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textResultActionPerformed

    private void bntigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntigualActionPerformed
        // TODO add your handling code here:
         Calcula(op);
//        textResult.setText("");
    }//GEN-LAST:event_bntigualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt0;
    private javax.swing.JButton bnt1;
    private javax.swing.JButton bnt2;
    private javax.swing.JButton bnt3;
    private javax.swing.JButton bnt4;
    private javax.swing.JButton bnt5;
    private javax.swing.JButton bnt6;
    private javax.swing.JButton bnt7;
    private javax.swing.JButton bnt8;
    private javax.swing.JButton bnt9;
    private javax.swing.JButton bntAdc;
    private javax.swing.JButton bntC;
    private javax.swing.JButton bntDiv;
    private javax.swing.JButton bntMult;
    private javax.swing.JButton bntPonto;
    private javax.swing.JButton bntSub;
    private javax.swing.JButton bntVoltar;
    private javax.swing.JButton bntigual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField textResult;
    // End of variables declaration//GEN-END:variables
}
